### ISSUE TITLE
Continuing issues with streaming post v1.4.117

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tripodtr/npr-android-app#56]
```
I did update my phone to the new version.  I get an error 38, 0 for WAMU and 
error 351.4.  The stream just doesn’t play except for Bluegrass stream which 
I didn’t get any issues.  I tested a few more stations and got the error 
message but after a few seconds I got the audio.  WAMU just never played.



Andrea
aivy@npr.org

Andrea 



Phone type  LG Optimus
Android Version: 2.2.1
Baseband version: LS670MV9_6040
Kernel Version:2.6.32.9  le@android-build #2 
Build Number: FRG83


```

Original issue reported on code.google.com by `kate.my...@gmail.com` on 5 Jan 2011 at 10:28

**Comment by GoogleCodeExporter** [comment]
```
May duplicate previous issue.
```

Original comment by `kate.my...@gmail.com` on 5 Jan 2011 at 10:28

**Comment by GoogleCodeExporter** [comment]
```
On a Droid running 2.2.1 all of WAMU plays for me, but I don't get any 
pre-rolls.
```

Original comment by `jpenn...@gmail.com` on 6 Jan 2011 at 7:52

**Comment by GoogleCodeExporter** [comment]
```
I'm changing the name of this tread to include all issues with streaming. I'll 
add some of the user feedback I've received.
```

Original comment by `jpenn...@gmail.com` on 6 Jan 2011 at 7:56
- Changed title: **Continuing issues with streaming post v1.4.117**
- Added labels: **Priority-Critical**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Via email on 1/6/11:

Still force closes on HTL Hero even after latest update .1/5/11
```

Original comment by `jpenn...@gmail.com` on 6 Jan 2011 at 7:59

**Comment by GoogleCodeExporter** [comment]
```
Via email on 1/6/11:

To whom it may concern,

I love your application but the streaming is still broke. Please correct this 
at once.

Thank you
```

Original comment by `jpenn...@gmail.com` on 6 Jan 2011 at 8:02

**Comment by GoogleCodeExporter** [comment]
```
Via email on 1/6/11:

I absolutely love your app, but recently an update has corrupted it causing a 
force close with every attempt to open the app.  I use a HTC Hero with Sprint.  
If there is something that I can do please advise, otherwise I eagerly look 
forward to an update that repairs this error.

Thank you,

```

Original comment by `jpenn...@gmail.com` on 6 Jan 2011 at 8:02

**Comment by GoogleCodeExporter** [comment]
```
Via email on 1/4/11:

Every time I try to stream a station I get the error of 1:1.  Can you tell me 
what tht means and how to fix it?
```

Original comment by `jpenn...@gmail.com` on 6 Jan 2011 at 8:11

**Comment by GoogleCodeExporter** [comment]
```
Stack trace from the dev portal in the Android Market: 

java.lang.RuntimeException: Unable to start activity 
ComponentInfo{org.npr.android.news/org.npr.android.news.Main}: 
java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2787)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2803)
at android.app.ActivityThread.access$2300(ActivityThread.java:135)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2136)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:144)
at android.app.ActivityThread.main(ActivityThread.java:4937)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at org.npr.android.news.ListenActivity.updatePlayTime(ListenActivity.java:397)
at 
org.npr.android.news.ListenActivity.onProgressChanged(ListenActivity.java:441)
at android.widget.SeekBar.onProgressRefresh(SeekBar.java:89)
at android.widget.ProgressBar.doRefreshProgress(ProgressBar.java:506)
at android.widget.ProgressBar.refreshProgress(ProgressBar.java:515)
at android.widget.ProgressBar.setProgress(ProgressBar.java:564)
at android.widget.ProgressBar.setProgress(ProgressBar.java:545)
at android.widget.ProgressBar.onRestoreInstanceState(ProgressBar.java:947)
at android.view.View.dispatchRestoreInstanceState(View.java:6137)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:1217)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:1217)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:1217)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:1217)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:1217)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:1217)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:1217)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:1217)
at android.view.View.restoreHierarchyState(View.java:6116)
at 
com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.j
ava:1496)
at android.app.Activity.onRestoreInstanceState(Activity.java:850)
at android.app.Activity.performRestoreInstanceState(Activity.java:822)
at 
android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.j
ava:1142)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2765)
... 11 more
```

Original comment by `jpenn...@gmail.com` on 7 Jan 2011 at 7:38

**Comment by GoogleCodeExporter** [comment]
```
Michael has sent around a patch for this issue.
```

Original comment by `jpenn...@gmail.com` on 7 Jan 2011 at 7:38

**Comment by GoogleCodeExporter** [comment]
```
Issue 53 has been merged into this issue.
```

Original comment by `jpenn...@gmail.com` on 31 Jan 2011 at 7:12

**Comment by GoogleCodeExporter** [comment]
```
via e-mail 4/12

1) "After upgrading my Android phone, I cannot play any stations."

The listener is using a Samsung Mesmerize with OS 2.0.1, Version code:15. He is 
trying to stream WVPM-FM Morgantown, WV 90.9 FM on both WiFi and 3G. He's not 
getting an error message but "There is a little curser moving in a circle like 
the system is trying 
to find the station" but it never plays.

2) Hello,

Using android, nexus s, 2.3.2. The streams of stations no longer work for
me. The audio sounds squeaky then stops after about give seconds. Love the
new look and the added shows, but miss the stream ability.

He was trying to listen to KOPB but did try multiple stations. He is using the 
latest version 2.0.1 and tried streaming both on WiFi and 3G. He is also not 
getting any error messages. 

3) "Updated Sunday.  After the update I can not stream live broadcasts more 
than 30 seconds. Running 
an HTC incredible."

Android version 2.2

Stations 89.3 WPNE Green Bay, 88.1 WHID Green Bay, and some 
random other ones just to see if it 
was the WPR stream.

No error message... Just maybe 20 seconds at most of 
audio, then some bips. whips, and maybe some 
more audio, or maybe not.

Tried streaming on 3G. 

```

Original comment by `erinnpr...@gmail.com` on 12 Apr 2011 at 2:38

**Comment by GoogleCodeExporter** [comment]
```
1) We're still getting reports of streams not working at all after the update
I am using android 2.2.1.
I have tried to stream WEVO and WBUR.
I am not getting any error message.
I can listen to the programming that you mentioned directly from NPR.
listens on 3G and WiFi

2) The OS is mototrola Blur.  The model is a Motorola Devour.  I am trying to 
stream KNOW from the 
Twin Cities.  No 
error messages.  Using Wi-Fi.  

I used to be able to stream programs no problem.  but when I updated to the new 
version of the NPR 
android app that 
was pushed out, I no longer had an option of streaming my programs.  Now it 
will 
only let me stream news stories.  
That's OK but I do miss listening to my favorite programs on my 
phone.  Sorry for being a pain.

3) I receive no error messages now, though I used 
to with the previous version of your app - typically 
a receive error. (I'm now using 2.0.2 V16 on a T-
Mobile Samsung Vibrant with Android 2.2).

Yes, I CAN listen to Hourly News and other programs 
from any station. I CAN NOT listen to WJCT-FM 
Jacksonville "Listen Live" and "Listen Online" nor 
can I listen to KCRW-FM Santa Monica "MP3 Stream" 
or "All-Music Channel" (the player says "Now 
Playing" but the little Java waiting circle just 
spins away in silence). However, I CAN listen to 
WWIO-AM St. Marys "Listen Online."

I get the same results over Wi-Fi and 3G.






```

Original comment by `erinnpr...@gmail.com` on 2 May 2011 at 3:02

**Comment by GoogleCodeExporter** [comment]
```
I have the same issues as Kate above, the only WAMU stream that works for me is 
the bluegrass country one.  WETA also does not work.

Droid Charge (SAMSUNG i510.06
Firmware: 2.2.1
Baseband: i510.06 V.EE4
Kernel: 2.6.32.9 imnut@virtualbox #1
Build: SCH-I510.EE4
```

Original comment by `alan.weh...@gmail.com` on 22 Jun 2011 at 1:26

**Comment by GoogleCodeExporter** [comment]
Original comment by `jpenn...@gmail.com` on 12 Apr 2012 at 7:55
- Changed state: **Backlog**
- Added labels: **Priority-High**
- Removed labels: **Priority-Critical**
