### ISSUE TITLE
2.0BETA force close with playlist reorder

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tripodtr/npr-android-app#67]
```
What steps will reproduce the problem?
1. add multiple items to playlist
2. reveal playlist
3. scroll playlist, say to the fifth entry
4. attempt reorder with grip, in either direction

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?

beta on emulator running 2.2

Please provide any additional information below.

FATAL EXCEPTION: mainjava.lang.NullPointerException
  at org.npr.android.widget.DragNDropListView.calculateDropBeforePosition(DragNDropListView.java:258)
  at org.npr.android.widget.DragNDropListView.drag(DragNDropListView.java:143)
  at org.npr.android.widget.DragNDropListView.onTouchEvent(DragNDropListView.java:103)
```

Original issue reported on code.google.com by `tjack1...@gmail.com` on 22 Mar 2011 at 5:31

**Comment by GoogleCodeExporter** [comment]
```
I couldn't get the FC issue here in testing the latest. We did fix an issue 
where dropping or slowly dragging over a divider would cause a FC. More 
noticeable on an HTC Incredible than N1 or G1 or Droid X in build 194.

I did notice that drag-and-drop really only works for the first visible items 
in the list and doesn't work at all when scrolled down a page. While I don't 
get an FC, that's definitely an issue we need to fix.
```

Original comment by `jeremy.w...@gmail.com` on 22 Mar 2011 at 5:48
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
I haven't heard more about this specifically so I'm marking it as closed. Lemme 
know if we need to reopen.
```

Original comment by `jpenn...@gmail.com` on 1 Apr 2011 at 3:28
- Changed state: **Fixed**
