### ISSUE TITLE
App crashes from program interactions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tripodtr/npr-android-app#82]
```
What steps will reproduce the problem? (synthesized from several user comments)
1. Go to a program (such as Radiolab specifically)
2. Attempting to play a segment or all segments
3. Crash

Here is a crashlog:

java.lang.NullPointerException
at org.npr.android.news.PlaybackService.isPlaylist(PlaybackService.java:648)
at 
org.npr.android.news.PlaybackService.prepareThenPlay(PlaybackService.java:330)
at org.npr.android.news.PlaybackService.playCurrent(PlaybackService.java:244)
at org.npr.android.news.PlaybackService.onHandleIntent(PlaybackService.java:202)
at 
org.npr.android.news.PlaybackService$ServiceHandler.handleMessage(PlaybackServic
e.java:131)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:143)
at android.os.HandlerThread.run(HandlerThread.java:60)


```

Original issue reported on code.google.com by `nprme...@gmail.com` on 8 Apr 2011 at 5:59

**Comment by GoogleCodeExporter** [comment]
```
I believe this is also related:

java.lang.RuntimeException: Error receiving broadcast Intent { 
act=org.npr.android.news.CHANGE (has extras) } in 
org.npr.android.news.PlaylistView$PlaybackChangeReceiver@45a56ba8
at 
android.app.ActivityThread$PackageInfo$ReceiverDispatcher$Args.run(ActivityThrea
d.java:942)
at android.os.Handler.handleCallback(Handler.java:587)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:143)
at android.app.ActivityThread.main(ActivityThread.java:4701)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at 
org.npr.android.news.PlaylistView$PlaybackChangeReceiver.onReceive(PlaylistView.
java:400)
at 
android.app.ActivityThread$PackageInfo$ReceiverDispatcher$Args.run(ActivityThrea
d.java:910)
... 9 more
```

Original comment by `nprme...@gmail.com` on 8 Apr 2011 at 6:02

**Comment by GoogleCodeExporter** [comment]
```
Any thoughts on this?
```

Original comment by `jpenn...@gmail.com` on 19 May 2011 at 7:58

**Comment by GoogleCodeExporter** [comment]
```
I cannot repro this, using the provided steps, in the current build on Android 
OS 2.3.4 on Nexus One. Also, the line number given in the first stack trace 
doesn't match the latest code.

The first error suggests that there is no URL at all for the stream which 
implies to me that there was something wrong with the feed?

I'm not sure where the second error could have caused a problem unless the 
broadcast receiver was called *after* the activity finished. Likely that's a 
carry-on error because of the first error killing the app.
```

Original comment by `jeremy.w...@gmail.com` on 19 May 2011 at 8:14

**Comment by GoogleCodeExporter** [comment]
```
Can't duplicate. Will continue to monitor publisher tools for new crashes.
```

Original comment by `jpenn...@gmail.com` on 22 Jun 2011 at 3:21
- Changed state: **WontFix**
